[piri.plugins]
scratchpads = true

[scratchpads.term]
direction = "fromRight"
animation_enabled = false
command = "kitty"
app_id = "kitty" 
size = "40% 50%"
margin = 50
auto_hide_on_focus_loss = true

[scratchpads.editor]
direction = "fromLeft"
animation_enabled = false
command = "gnome-text-editor"
app_id = "org.gnome.TextEditor"
size = "40% 50%"
margin = 50
auto_hide_on_focus_loss = true

[scratchpads.pip]
direction = "fromRight"
animation_enabled = false
command = ""
app_id = ".*zen.*|.*firefox.*"
title = ".*Picture-in-Picture.*"
size = "40% 40%"
margin = 30
auto_hide_on_focus_loss = true
