[piri.plugins]
scratchpads = true

[scratchpads.term]
direction = "fromRight"
animation_enabled = false
command = "kitty --class piri-term"
app_id = "piri-term" 
size = "40% 50%"
margin = 50
auto_hide_on_focus_loss = true

[scratchpads.editor]
direction = "fromLeft"
animation_enabled = false
command = "gnome-text-editor"
app_id = "org.gnome.TextEditor"
size = "40% 50%"
margin = 50
auto_hide_on_focus_loss = true
